include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
    ref: v26.0.1

variables:
  CI_RENOVATE_IMAGE: 'ghcr.io/renovatebot/renovate:43.198.0'
  LOG_LEVEL: 'debug'
  RENOVATE_EXTRA_FLAGS: 'MalteJoe/Renovate-Reproduction-Terraform-Provider-Hashes'
