include:
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
    ref: v26.0.1

variables:
  RENOVATE_AUTODISCOVER: 'true'
  RENOVATE_AUTODISCOVER_NAMESPACES: 'MalteJoe'
